### ISSUE TITLE
Am trying to open index.html on localhost

### ISSUE THREAD

**Issue by olwen1987** [razagill/react-phone-input#11]
Hi,
I am trying to open the Index.html and expecting to see the phone input. But i dont think the demo is complete. If that is so i will work and fix the demo as well with different options.

Regards,
Aaron

**Comment by sample-usr** [comment]
Hi @olwen1987 sorry that there aren't any contribution guidelines yet, I'm working on that. You are not seeing the component because for production it's commented in [https://github.com/razagill/react-phone-input/blob/master/src/index.js](url).
Just uncomment:

```
// ReactDOM.render(
//   <ReactPhoneInput defaultCountry={'us'} preferredCountries={['us', 'de']} excludeCountries={'in'}/>,
//   document.getElementById('content'));
```

And run `npm run build`.

Alternatively you can just run `npm run dev` which will start a webpack-dev-server (you'll still need to uncomment the rendering part).
