### ISSUE TITLE
Reseting value in the phone input

### ISSUE THREAD

**Issue by maxcmoi89** [razagill/react-phone-input#14]
Hi,

Firstly, I would like to thank you for having made this very nice phone input.

Secondly, I was wondering if it was possible to reset the phone input for the ReactPhoneInput component?

I embedded the component like this:

```
<ReactPhoneInput ref="phone"
                 defaultCountry={"be"}
                 onlyCountries={['be', 'nl', 'gb', 'lu', 'fr', 'de']}
                 onChange={this._changePhone}
                 value={this.props.phone}
/>
```

I thought that if I cleared this.props.phone then the input field would be reset but that is not the case. Do you have an idea on how I could achieve a reset of the component? Thank you,

**Comment by sample-usr** [comment]
Hi @maxcmoi89 thanks for your appreciation.
Sadly there isn't a direct way to clear out the input programmatically right now since a lot of computations happen on the initial launch. You could possibly set your `this.props.phone`, get the reference of the inner `input` field directly via `findDOMNode` and fire the `change` event.

```
let changeEvent = new Event('change');
innerInputField.dispatchEvent(changeEvent);
```

This should handle the formatting for the component in a better way too.

**Comment by maxcmoi89** [comment]
I struggled quite a bit with this, so I decided to alter the react-phone-input component a little.

I added this function to the component class : 

```
  resetNumber() {
    let formattedNumber = this.formatNumber(this.state.selectedCountry.dialCode, this.state.selectedCountry.format);
    this.setState({
      formattedNumber: formattedNumber
    })
  }
```

and this bit in the constructor : 
`this.resetNumber = this.resetNumber.bind(this);
`

It works like a charm. Now when I do a this.refs.phone.resetNumber(), with phone being my ref for the component, it resets the phone number. I think it would be useful to add this to the component so I submitted a PR with my changes.
